In [ ]:
a=[1,2,3,4,5,6]

In [ ]:
print(a)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(a[0]) #indexing

1


In [ ]:
print(a[0:3]) #slicing(0이상3미만)

[1, 2, 3]


In [ ]:
for i in [1,2,3,4,5]:
  print(i)

1
2
3
4
5


In [ ]:
def add(m,n): #function
  return m+n

In [ ]:
add(3,4)

7

In [ ]:
b=[[2, 4],[10,12]]
print(b)

[[2, 4], [10, 12]]


In [ ]:
import numpy as np
c=np.array([[2,4],[10,12]])
print(c)

[[ 2  4]
 [10 12]]


In [ ]:
print(c*2)

[[ 4  8]
 [20 24]]


In [ ]:
print(c+2)

[[ 4  6]
 [12 14]]


In [ ]:
print(c[0][0])

2


In [ ]:
print(c[1][1])

12


In [ ]:
print(c.shape)

(2, 2)


In [ ]:
print(c.T)

[[ 2 10]
 [ 4 12]]


In [ ]:
#_________________________________________

In [ ]:
class naegul:
  def __init__(self):
    self.Type='animal'
  def speak(self):
    print('얼렁 일해서 돈 갚아라')
  def whoareyou(self):
    print(self.Type)

In [ ]:
naegul2=naegul()

In [ ]:
naegul2.speak()

얼렁 일해서 돈 갚아라


In [ ]:
naegul2.whoareyou()

animal
